use_frameworks!

platform :ios, '13.0'

target 'TGSPublic_Example' do
  pod 'TGSPublic', :path => '../'

  target 'TGSPublic_Tests' do
    inherit! :search_paths

    
  end
end
deployment_target = '13.0'
#以下在M1的mac上需要使用
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
#                config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"  不加这个可以模拟器运行
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
